{% set name = "cramjam" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c82500ed91605c2d9781380b378397012e25127e89d64f460fea6aeac4389b4

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  skip: true # [py<38]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin >=0.14
    - cargo-bundle-licenses
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - cramjam
  commands:
    # Added in order to select the hypothesis profile
    # https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.deadline
    - export CI=1. # [not win]
    - set CI="1"
    - pip check
    - pytest -v -n auto tests
  requires:
    - pip
    - pytest >=5.30
    - numpy
    - pytest-xdist
    - hypothesis

about:
  home: https://github.com/milesgranger/cramjam
  license: MIT
  license_family: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  summary: python bindings to rust-implemented compression
  description: |
    Extremely thin Python bindings to de/compression algorithms in Rust.
    Allows for using algorithms such as Snappy, without any system dependencies.
  dev_url: https://github.com/milesgranger/cramjam
  doc_url: https://docs.rs/cramjam/latest/cramjam

extra:
  recipe-maintainers:
    - martindurant
    - milesgranger
  skip-lints:
    - host_section_needs_exact_pinnings
